name: Benchmark Shell Bash Script
on:
  push:
    branches: [ main ]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - uses: snok/install-poetry@v1
        with:
          version: 1.1.13
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Install Poetry and Run Make File
        run: |
          poetry --version
          cd benchmark/
          sh benchmark.sh main 117-benchmarking
