name: Benchmark Pull Request
on:
  pull_request:

env:
  main_hash: "$(/usr/bin/git log -1 --format='%H')"
  path_hash: "$(/usr/bin/git log -1 --format='benchmark/%H.csv')"

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
#          repository: flooie/pingme
#          ref: artifacts
          repository: freelawproject/eyecite
          ref: baseline-benchmarking
      - uses: actions/setup-python@v2
      - uses: snok/install-poetry@v1
        with:
          version: 1.2.0rc1
          virtualenvs-create: true
          virtualenvs-in-project: true


      - name: Run stuff for PR
        run: |
          echo "${{ env.main_hash }}"
          echo "${{ env.main_hash }}"
          echo "${{ env.path_hash }}"
          curl https://github.com/freelawproject/eyecite/blob/artifacts/benchmark/pr${{github.event.number}}-${{ env.main_hash }}.csv?raw=true --fail --output benchmark/${{ env.main_hash }}.csv


      - name: Run Benchmark Script
        run: |
          echo "${{ env.main_hash }}"
          echo "benchmark/${{ env.main_hash }}.csv"
          curl https://storage.courtlistener.com/bulk-data/eyecite/tests/one-percent.csv.bz2 --output benchmark/bulk-file.csv.bz2
          poetry install --with benchmark --without dev
          poetry run python benchmark/benchmark.py --branch "$(/usr/bin/git log -1 --format='%H')"

      - name: Upload and Post Files to PR
        uses: gavv/pull-request-artifacts@v1.0.0
        with:
          commit: ${{ github.event.pull_request.head.sha }}
          repo-token: ${{ secrets.TOKEN }}
          artifacts-branch: artifacts
          artifacts-dir: benchmark
          artifacts: |
            "${{ env.path_hash }}"


#      - uses: actions/checkout@v3
#        with:
#          repository: freelawproject/eyecite
#          ref: baseline-benchmarking
#
#      - name: Run Benchmark Script
#        run: |
#          echo "Checking out same branch again to see if any of my files are still there...."
#          pwd
#          cd benchmark
#          pwd
#          ls
          

#      - name: Run Benchmarking Script
#        run: |
#          curl https://storage.courtlistener.com/bulk-data/eyecite/tests/ten-percent.csv.bz2 --output benchmark/bulk-file.csv.bz2
#
#          git clone https://github.com/freelawproject/eyecite.git benchmark/eyecite
#          cp benchmark/benchmark.py benchmark/eyecite/ && cd benchmark/eyecite/
#          poetry install --no-dev
#          poetry run pip install matplotlib pandas tabulate
#
#          poetry run python benchmark.py
#
#          poetry install --no-dev
#          poetry run python benchmark.py --branch
#          poetry run python benchmark.py --chart
#
#      - name: Embed Timing Chart into Markdown Post
#        run: |
#          echo "![image](https://github.com/freelawproject/eyecite/blob/artifacts/benchmark/pr${{github.event.number}}-time-comparison.png?raw=true)" >> benchmark/outputs/report.md
#
#      - name: Upload and Post Files to PR
#        uses: gavv/pull-request-artifacts@v1.0.0
#        with:
#          commit: ${{ github.event.pull_request.head.sha }}
#          repo-token: ${{ secrets.GITHUB_TOKEN }}
#          artifacts-branch: artifacts
#          artifacts-dir: benchmark
#          artifacts: |
#            benchmark/outputs/report.md
#            benchmark/outputs/time-comparison.png
#            benchmark/outputs/output.csv
#            benchmark/outputs/main.csv
#            benchmark/outputs/branch.csv
#
#      - name: Add or Update PR Comment from Generated Report
#        uses: marocchino/sticky-pull-request-comment@v2
#        with:
#          recreate: true
#          path: benchmark/outputs/report.md

