name: Benchmark Pull Request
on:
  pull_request:

env:
  main: "$(/usr/bin/git log -1 --format='%H')"

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
#          repository: flooie/pingme
#          ref: artifacts
          repository: freelawproject/eyecite
          ref: baseline-benchmarking
      - uses: actions/setup-python@v2
      - uses: snok/install-poetry@v1
        with:
          version: 1.2.0rc1
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Run stuff for PR
        id: curl-csv
        continue-on-error: true
        run: |
          curl "https://raw.githubusercontent.com/flooie/pingme/artifacts/benchmark/${{ env.main }}.csv?raw=true" --output "benchmark/${{ env.main }}.csv"
          cat benchmark/${{ env.main }}.csv

      - name: Run Benchmark Script
        if: steps.curl-csv.outcome != 'success'
        run: |
          curl https://storage.courtlistener.com/bulk-data/eyecite/tests/one-percent.csv.bz2 --output benchmark/bulk-file.csv.bz2
          poetry install --with benchmark --without dev
          poetry run python benchmark/benchmark.py --branch ${{ env.main }}
          cat benchmark/${{ env.main }}.csv

      - name: Update Main CSV File
        if: steps.curl-csv.outcome != 'success'
        uses: test-room-7/action-update-file@v1
        with:
            file-path: benchmark/*.csv
            commit-msg: Update File
            github-token: ${{ secrets.TOKEN }}
            branch: artifacts

      - uses: actions/checkout@v3
        with:
          repository: freelawproject/eyecite
          ref: baseline-benchmarking
#
      - name: Curl File again
        run: |
          curl https://storage.courtlistener.com/bulk-data/eyecite/tests/one-percent.csv.bz2 --output benchmark/bulk-file.csv.bz2
#
      - name: Benchmark Prooftest
        run: |
          poetry install --with benchmark --without dev
          poetry run python benchmark/benchmark.py --branch abcxyz
          cat benchmark/abcxyz.csv

      - name: Curl and Compare old hash csv
        run: |
          curl "https://raw.githubusercontent.com/flooie/pingme/artifacts/benchmark/${{ env.main }}.csv?raw=true" --output "benchmark/${{ env.main }}.csv"
          poetry run python benchmark/benchmark.py --main ${{ env.main }} --branch abcxyz --chart
          cat benchmark/report.md

      - name: Add or Update PR Comment from Generated Report
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          recreate: true
          path: benchmark/report.md

