name: Benchmark Pull Request
on:
  push:

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: freelawproject/eyecite
          ref: baseline-benchmarking

      - uses: actions/setup-python@v2
      - uses: snok/install-poetry@v1
        with:
          version: 1.2.0rc1
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Run Benchmark Script
        run: |
          curl https://storage.courtlistener.com/bulk-data/eyecite/tests/one-percent.csv.bz2 --output benchmark/bulk-file.csv.bz2
          poetry install --with benchmark --without dev
          poetry run python benchmark/benchmark.py --branch abc
          poetry run python benchmark/benchmark.py --branch xyz
          poetry run python benchmark/benchmark.py --main abc --branch xyz --chart

          cat benchmark/report.md


#      - name: Run Benchmarking Script
#        run: |
#          curl https://storage.courtlistener.com/bulk-data/eyecite/tests/ten-percent.csv.bz2 --output benchmark/bulk-file.csv.bz2
#
#          git clone https://github.com/freelawproject/eyecite.git benchmark/eyecite
#          cp benchmark/benchmark.py benchmark/eyecite/ && cd benchmark/eyecite/
#          poetry install --no-dev
#          poetry run pip install matplotlib pandas tabulate
#
#          poetry run python benchmark.py
#
#          poetry install --no-dev
#          poetry run python benchmark.py --branch
#          poetry run python benchmark.py --chart
#
#      - name: Embed Timing Chart into Markdown Post
#        run: |
#          echo "![image](https://github.com/freelawproject/eyecite/blob/artifacts/benchmark/pr${{github.event.number}}-time-comparison.png?raw=true)" >> benchmark/outputs/report.md
#
#      - name: Upload and Post Files to PR
#        uses: gavv/pull-request-artifacts@v1.0.0
#        with:
#          commit: ${{ github.event.pull_request.head.sha }}
#          repo-token: ${{ secrets.GITHUB_TOKEN }}
#          artifacts-branch: artifacts
#          artifacts-dir: benchmark
#          artifacts: |
#            benchmark/outputs/report.md
#            benchmark/outputs/time-comparison.png
#            benchmark/outputs/output.csv
#            benchmark/outputs/main.csv
#            benchmark/outputs/branch.csv
#
#      - name: Add or Update PR Comment from Generated Report
#        uses: marocchino/sticky-pull-request-comment@v2
#        with:
#          recreate: true
#          path: benchmark/outputs/report.md

