name: Benchmark Pull Request
on:
  pull_request:

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: snok/install-poetry@v1
        with:
          version: 1.1.13
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Run Benchmarking Script
        run: |
          curl https://storage.courtlistener.com/bulk-data/eyecite/tests/ten-percent.csv.bz2 --output benchmark/bulk-file.csv.bz2
          
          git clone https://github.com/freelawproject/eyecite.git benchmark/eyecite
          cp benchmark/benchmark.py benchmark/eyecite/ && cd benchmark/eyecite/
          poetry install --no-dev          
          poetry run python benchmark.py --branch main

          git checkout ${{ github.head_ref }}
          poetry install --no-dev
          poetry run python benchmark.py --branch ${{ github.head_ref }} && cd ..

          poetry init --no-interaction
          poetry add matplotlib pandas tabulate
          poetry install --no-dev
          
          poetry run python chart.py --branch1 main --branch2 ${{ github.head_ref }}

      - name: Embed Timing Chart into Markdown Post
        run: |
          echo "![image](https://github.com/flooie/pingme/blob/artifacts/benchmark/pr${{github.event.number}}-time-comparison.png?raw=true)" >> benchmark/outputs/report.md

      - name: Upload and Post Files to PR
        uses: gavv/pull-request-artifacts@v1.0.0
        with:
          commit: ${{ github.event.pull_request.head.sha }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          artifacts-branch: artifacts
          artifacts-dir: benchmark
          artifacts: |
            benchmark/outputs/report.md
            benchmark/outputs/time-comparison.png
            benchmark/outputs/output.csv

      - name: Add or Update PR Comment from Generated Report
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          recreate: true
          path: benchmark/outputs/report.md

