name: Benchmark Pull Request
on:
  pull_request:

env:
  main: "$(/usr/bin/git log -1 --format='%H')"

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
#          repository: flooie/pingme
#          ref: artifacts
          repository: freelawproject/eyecite
          ref: baseline-benchmarking
      - uses: actions/setup-python@v2
      - uses: snok/install-poetry@v1
        with:
          version: 1.2.0rc1
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Run stuff for PR
        run: |
          curl https://storage.courtlistener.com/bulk-data/eyecite/tests/one-percent.csv.bz2 --output benchmark/bulk-file.csv.bz2
          poetry install --with benchmark --without dev
          poetry run python benchmark/benchmark.py --branch PR
          git checkout baseline-benchmarking
          poetry run pip install reporters-db==3.2.10
          poetry run python benchmark/benchmark.py --branch main
          poetry run python benchmark/benchmark.py --main main --branch PR --chart

      - name: Add or Update PR Comment from Generated Report
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          recreate: true
          path: |
            benchmark/report.md
            benchmark/time-comparison.png
            benchmark/branch.csv
            benchmark/main.csv
            benchmark/output.csv
