
name: GitHub Actions Demo
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: |
          pip install -r requirements.txt
          python3 benchmark.py

      - uses: actions/checkout@v3
        with:
          ref: main
      - run: |
          python3 benchmark.py

      - run: | 
          ls 
