name: Branches Upload on Main
on:
  push:
    branches: [ main ]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2

      - run: |
          echo "${{ env.hash }}"

      - run: |
          pip install -r requirements.txt
          pip install git+https://github.com/freelawproject/eyecite@${{ env.hash }}
          python3 benchmark.py --main

      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: /home/runner/work/pingme/pingme/corpus/plotted_A.csv
