name: Branches Upload on Main
on:
  push:
    branches: [ main ]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2

      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --verify HEAD)"
      - name: Check outputs
        run: echo ${{ steps.vars.outputs.sha_short }}

      - run: |
          pip install -r requirements.txt
#          "pip install git+https://github.com/freelawproject/eyecite@${{ steps.vars.outputs.sha_short }}"
          "pip install git+https://github.com/freelawproject/eyecite@3e2a031c11e69523eb71450d3c20e4856c85c9a5
          python3 benchmark.py --main

      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: /home/runner/work/pingme/pingme/corpus/plotted_A.csv
