#name: Compare to Main Branch
#on: ["push"]
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-python@v2
#        run: |
#          pip install -r requirements.txt
#          python3 benchmark.py

name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: |
          pip install -r requirements.txt
          python3 benchmark.py

      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Switch to Main
      - uses: actions/setup-python@v2
      - uses: actions/checkout@main
      - run: |
          pip install -r requirements.txt
          python3 benchmark.py
