name: Check Me
on:
  pull_request:

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Lets Run Test
        run: |
          python benchmark/stuff.py