name: Check Me
on:
  pull_request:

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout tools repo
        uses: actions/checkout@v3

      - name: Run stuff for PR
        run: |
          python benchmark/stuff.py
          echo ${{ github.sha }}
          echo ${{ github.ref }}
          echo ${{ github.event.pull_request.head.sha }}
          echo "GITHUB_SHA_SHORT=$(/usr/bin/git log -1 --format='%H')" >> GITHUB_ENV
          python benchmark/stuff.py --something 1234
          python benchmark/stuff.py --something $GITHUB_SHA_SHORT

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Run Stuff for Main
        run: |
          python benchmark/stuff.py --something 1234
          python benchmark/stuff.py --something $GITHUB_SHA_SHORT

#          echo ${{ github.sha }}
#          echo ${{ github.ref }}
#          echo ${{ github.event.pull_request.head.sha }}
#          /usr/bin/git log -2 --format='%H'
#          echo "GITHUB_SHA_SHORT=$(/usr/bin/git log -2 --format='%H')" >> GITHUB_ENV
#
#      - name: Show GitHub context
#        env:
#          GITHUB_CONTEXT: ${{ toJson(github) }}
#        run: |
#          echo "$GITHUB_CONTEXT"
#          echo ${{ env.GITHUB_SHA_SHORT }}
#
#      - name: Set env
#        run: echo "GITHUB_SHA_SHORT=$(echo /usr/bin/git log -2 --format='%H')" >> $GITHUB_ENV
#      - name: Test
#        run: |
#          echo ${{ env }}
#          echo ${{ env.GITHUB_SHA_SHORT }}
#          echo $GITHUB_SHA_SHORT
#      - name: Tes
#        if: ${{ env.GITHUB_SHA_SHORT == '2b8bf106af86963f4086bad0492bc47cb97c1d3d' }}
#        run: |
#          echo "it worked"
#
#      - name: Test
#        run: echo ${{ env.GITHUB_SHA_SHORT }}
#      - name: Test2
#        run: |
#          echo "action_state=yellow" >> $GITHUB_ENV
#
#      - name: Use the valuex
#        run: |
#          echo "${{ env.action_state }}"
