name: Check Me
on:
  push:

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout tools repo
        uses: actions/checkout@v3

      - name: Run stuff for Main
        run: |
          python benchmark/stuff.py

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: checkme

      - name: Run Stuff for Check Me
        run: |
          python benchmark/stuff.py
