name: Check Me
on:
  push:

env:
  main_hash: "$(/usr/bin/git log -1 --format='https://github.com/freelawproject/pingme/blob/artifacts/benchmark/%H.csv?raw=true')"
  main: "$(/usr/bin/git log -1 --format='%H')"

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout tools repo
        uses: actions/checkout@v3

      - name: Run stuff for PR
        id: xyz
        run: |
          echo ${{ env.main_hash }}
          echo "${{ env.main_hash }}"
          curl ${{ env.main_hash }} --output "benchmark/abc.csv"
          curl "https://github.com/freelawproject/pingme/blob/artifacts/benchmark/${{ env.main }}.csv?raw=true" --output "benchmark/xyz.csv"
          cd benchmark
          ls

#          run: echo "::set-output name=p-address::"https://github.com/freelawproject/pingme/blob/artifacts/benchmark/${{ env.main_hash }}.csv?raw=true"
#          echo "${{ env.main_hash }} and this and this"
#          echo "https://github.com/freelawproject/pingme/blob/artifacts/benchmark/${{ env.main_hash }}.csv?raw=true"
#          echo "https://github.com/freelawproject/pingme/blob/artifacts/benchmark/$main_hash.csv?raw=true"
#          foo="${env.main_hash} World"
#          echo ${foo}
