name: Check Me
on:
  pull_request:

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout tools repo
        uses: actions/checkout@v3

      - name: Run stuff for PR
        run: |
          python benchmark/stuff.py
          echo ${{ github.sha }}
          echo ${{ github.ref }}

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0

      - name: Run Stuff for Main
        run: |
          python benchmark/stuff.py
          echo ${{ github.sha }}
          echo ${{ github.ref }}
          echo ${{ github.event.head_commit }}
          echo ${{ github.event.head_commit.message }}
          a=/usr/bin/git log -1 --format='%H'
          echo $a