name: Check Me
on:
  pull_request:

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main
        uses: actions/checkout@v3
        with:
          path: main
        run: |
          python benchmark/stuff.py

      - name: Checkout PR
        uses: actions/checkout@v3
        run: |
          python benchmark/stuff.py
          
