name: Check Me
on:
  push:

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout tools repo
        uses: actions/checkout@v3

      - name: Run stuff for PR
        run: |
          python benchmark/stuff.py

      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: checkme
        run: |
          python benchmark/stuff.py
