name: Just Comment
on:
  push
jobs:
    push-comment:
      runs-on: ubuntu-latest
      steps:
        - name: Just make a comment
          uses: marocchino/sticky-pull-request-comment@v2
          with:
            GITHUB_TOKEN: ${{ secrets.TOKEN }}
            recreate: true
            repo: crosspingme
            message: "Hello world...."
            number: 1