name: Remote Dispatch Action Responder

on: [repository_dispatch]

jobs:
  ping-pong:
    runs-on: ubuntu-latest
    steps:
      - name: Event Information xxxx
        run: |
          echo "Event '${{ github.event.action }}' received from '${{ github.event.client_payload.repository }}'"
          echo ${{ github.event.action }}

      - name: PONG - Dispatch response to received PING
        if: github.event.action == "pr1"
        run: |
          echo "I certainly am going to run something"
          echo "Event '${{ github.event.action }}' received from '${{ github.event.client_payload.repository }}'"
