name: Make File Testing
on:
  push:
    branches: [ main ]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: snok/install-poetry@v1
        with:
          version: 1.1.13
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Check outputs
        run: |
          poetry --version
          make development --file other/Makefile -e ref1=update-courts-reporters-db ref2=main
