name: Download and process artifact
on:
  pull_request:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: snok/install-poetry@v1
        with:
          version: 1.1.13
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Install Poetry and Run Make File
        run: |
          make development --file other/Makefile -e ref1=update-courts-reporters-db ref2=main
      - run: |
          ls
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            Hello world ! :wave:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Edit PR comment
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: 'Content loaded ! (edited)'
          comment_includes: 'Loading'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Comment a pull_request
        uses: mb2dev/github-action-comment-pull-request@1.0.0
        with:
          message: "Hello, It's my first comment with Github action !"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          reactions: "+1 | -1 | laugh | hooray | confused | heart | rocket | eyes"