name: Download and process artifact
on:
  pull_request:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: snok/install-poetry@v1
        with:
          version: 1.1.13
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Install Poetry and Run Make File
        run: |
          cd benchmark/
          sh benchmark.sh main 117-benchmarking
      - run: |
          ls

      - name: Comment on the PR with file PR
        uses: machine-learning-apps/pr-comment@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path: benchmark/outputs/report.md

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            Hello world ! :wave:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Edit PR comment
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: 'Content loaded ! (edited)'
          comment_includes: 'Loading'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Comment a pull_request
        uses: mb2dev/github-action-comment-pull-request@1.0.0
        with:
          message: "Hello, It's my first comment with Github action !"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          reactions: "+1 | -1 | laugh | hooray | confused | heart | rocket | eyes"

      - uses: actions/upload-artifact@v3
        with:
          name: time-chart
          path: /home/runner/work/pingme/pingme/benchmark/outputs/time-comparison.png


      - name: PR comment with reactions
        uses: thollander/actions-comment-pull-request@v1
        env:
          pull_number: ${{github.event.number}}
        with:
          message: |
            This is the output of the speed comparison between the main branch and your PR.  
            Please take the time to review the chart for slow downs, speedups or 
            unexpected changes
            `$pull_number`
            ${{pull_number}}
            `${{pull_number}}`
            "![image](https://github.com/flooie/pingme/blob/main/pr`$pull_number`-time-comparison.png?raw=true) :wave:"
          reactions: eyes, rocket
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
