name: PyPI
on:
  push:
    tags:
      - v*.*.*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: |
          curl -s --form-string "token=${{ secrets.TOKEN }}" --form-string "user=${{ secrets.USER }}" --form-string "message=website changed"  https://api.pushover.net/1/messages.json
          
