name: Repository Dispatch
on:
  repository_dispatch:
    types: [my-event] # this is tagged event type to do the soemthing or other
jobs:
  myEvent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo ${{ github.event.client_payload.sha }}
          echo "hello world"
          echo ${{ github.event.client_payload.ref }}

      - name: Add or Update PR Comment from Generated Report
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          recreate: true
          repo: flooie/crosspingme
          message: "Hello world...."
          number: 1