name: Repository Dispatch
on:
  repository_dispatch:
    types: [reporters-db-pr] # this is tagged event type to do the soemthing or other
jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: snok/install-poetry@v1
        with:
          version: 1.1.13
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Run Benchmarking Script
        run: |
          curl https://storage.courtlistener.com/bulk-data/eyecite/tests/one-percent.csv.bz2 --output benchmark/bulk-file.csv.bz2
#          git clone https://github.com/freelawproject/eyecite.git benchmark/eyecite
#          cp benchmark/benchmark.py benchmark/eyecite/ && cd benchmark/eyecite/
#          poetry install --no-dev
#          poetry run pip install matplotlib pandas tabulate
          poetry run python benchmark.py 
               
#               checkout branch
          poetry run python benchmark.py
               
          poetry run python benchmark.py --chart

      - name: Embed Timing Chart into Markdown Post
        run: |
          echo "![image](https://github.com/flooie/pingme/blob/artifacts/benchmark/pr${{github.event.number}}-time-comparison.png?raw=true)" >> benchmark/outputs/report.md

      - name: Upload and Post Files to PR
        uses: gavv/pull-request-artifacts@v1.0.0
        with:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          commit: ${{ github.event.pull_request.head.sha }}
#          repo-token: ${{ secrets.TOKEN }}
          repo: crosspingme
          artifacts-branch: artifacts
          artifacts-dir: benchmark
          artifacts: |
            benchmark/outputs/report.md
            benchmark/outputs/time-comparison.png
            benchmark/outputs/output.csv
            benchmark/outputs/main.csv
            benchmark/outputs/branch.csv

      - name: Add or Update PR Comment from Generated Report
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          recreate: true
          repo: crosspingme
          message: "Hello world.... and hello more world '${{ github.event.client_payload.sha }}'"
          number: 1
