name: Repository Dispatch
on:
  repository_dispatch:
    types: [reporters-db-pr] # this is tagged event type to do the soemthing or other
jobs:
  myEvent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Add or Update PR Comment from Generated Report
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          recreate: true
          repo: crosspingme
          message: "Hello world.... and hello more world"
          number: 1