name: Download and process artifact
on:
  pull_request:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: snok/install-poetry@v1
        with:
          version: 1.1.13
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install Poetry and Run Make File
        run: |
          echo ${{ github.base_ref }}
          echo ${{ github.head_ref }}
          echo ${{ github.ref_name }}
          cd benchmark/
          sh benchmark.sh main 117-benchmarking

      - name: Update report and add link to chart
      - run: |
          echo "\n\n# Speed Comparison" >> /home/runner/work/pingme/pingme/benchmark/outputs/report.md
          echo "-------------------" >> /home/runner/work/pingme/pingme/benchmark/outputs/report.md
          echo "### Main Branch vs. Current Branch" >> /home/runner/work/pingme/pingme/benchmark/outputs/report.md
          echo "![image](https://github.com/flooie/pingme/blob/main/pr${{github.event.number}}-time-comparison.png?raw=true)" >> /home/runner/work/pingme/pingme/benchmark/outputs/report.md

      - name: Pull request artifacts
        if: ${{ github.event_name == 'pull_request' }}
        uses: gavv/pull-request-artifacts@v1.0.0
        with:
          commit: ${{ github.event.pull_request.head.sha }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: |
            /home/runner/work/pingme/pingme/benchmark/outputs/time-comparison.png
            /home/runner/work/pingme/pingme/benchmark/outputs/report.md
            benchmark/outputs/output.csv


      - name: Edit PR comment
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: "${{ steps.markdown_output.outputs.new_value }}"
          comment_includes: 'The Eyecite Report'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}