name: Download and process artifact
on:
  pull_request:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: snok/install-poetry@v1
        with:
          version: 1.1.13
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install Poetry and Run Make File
        run: |
          echo ${{ github.base_ref }}
          echo ${{ github.head_ref }}
          echo ${{ github.ref_name }}
          cd benchmark/
          sh benchmark.sh main 117-benchmarking

      - name: Display structure of downloaded files
        run: ls -R

      - name: Update Report MD
        run: |
          echo "\n\n" >> /home/runner/work/pingme/pingme/benchmark/outputs/report.md
          echo "# Speed Comparison" >> /home/runner/work/pingme/pingme/benchmark/outputs/report.md
          echo "-------------------" >> /home/runner/work/pingme/pingme/benchmark/outputs/report.md
          echo "### Main Branch vs. Current Branch" >> /home/runner/work/pingme/pingme/benchmark/outputs/report.md
          echo "![image](https://github.com/flooie/pingme/blob/main/pr${{github.event.number}}-time-comparison.png?raw=true)" >> /home/runner/work/pingme/pingme/benchmark/outputs/report.md

      - name: Pull request artifacts
        if: ${{ github.event_name == 'pull_request' }}
        uses: gavv/pull-request-artifacts@v1.0.0
        with:
          commit: ${{ github.event.pull_request.head.sha }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: |
            benchmark/outputs/report.md
            benchmark/outputs/time-comparison.png
            benchmark/outputs/output.csv

#      - name: Comment on the PR with file PR
#        uses: machine-learning-apps/pr-comment@master
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          path: benchmark/outputs/report.md


#      - name: Read file contents
#        id: read_file
#        uses: andstor/file-reader-action@v1
#        with:
#          path: "/home/runner/work/pingme/pingme/benchmark/outputs/report.md"
#
#      - name: File contents
#        run: cat /home/runner/work/pingme/pingme/benchmark/outputs/report.md


      - name: Get version
        id: vars
        run: echo ::set-output name=version::$(cat /home/runner/work/pingme/pingme/benchmark/outputs/report.md)
      - name: Test output
        run: echo ${{ steps.vars.outputs.version }}

      - name: Read file contents
        id: read_file
        uses: andstor/file-reader-action@v1
        with:
          path: "/home/runner/work/pingme/pingme/benchmark/outputs/report.md"


      - name: Edit PR comment
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: ${{ steps.read_file.outputs.contents }}
          comment_includes: 'The Eyecite Report'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}